version: '3'
services:
    registration-server:
        build: ./registration-server/src/main/docker
        working_dir: /registration-server/src/main/docker
        image: lesstraffic/registration-server:latest
        expose:
            - 8761
        ports:
            - 8761:8761
    configuration-server:
        build: ./configuration-server/src/main/docker
        working_dir: /configuration-server/src/main/docker
        image: lesstraffic/configuration-server:latest
        expose:
            - 8888
        ports:
            - 8888:8888
        depends_on:
            - registration-server
    gateway-server:
        build: ./gateway-server/src/main/docker
        working_dir: /gateway-server/src/main/docker
        image: lesstraffic/gateway-server:latest
        expose:
            - 8765
        ports:
            - 8765:8765
        depends_on:
            - registration-server
    geolocation-producer:
        build: ./geolocation-producer/src/main/docker
        working_dir: /geolocation-producer/src/main/docker
        image: lesstraffic/geolocation-producer:latest
        expose:
            - 8081
        ports:
            - 8081:8081
        depends_on:
            - registration-server
    geolocation-service:
        build: ./geolocation-service/src/main/docker
        working_dir: /geolocation-service/src/main/docker
        image: lesstraffic/geolocation-service:latest
        expose:
            - 9091
        ports:
            - 9091:9091
        depends_on:
            - registration-server